### ISSUE TITLE
does not build -> Could not resolve dependencies for project org.slj:mqtt-sn-gateway:jar:0.2.0:

### ISSUE THREAD

**Issue by pfostenberg** [simon622/mqtt-sn#58]
Hi,
try to build... as describe in README.md

Gateway Build

Git checkout the repository. For a simple standalone jar execution, run the following maven deps.
mvn -f mqtt-sn-codec clean install
mvn -f mqtt-sn-core clean install
-> OK so far.

mvn -f mqtt-sn-gateway clean package

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.065 s
[INFO] Finished at: 2023-02-01T20:14:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mqtt-sn-gateway: Could not resolve dependencies for project org.slj:mqtt-sn-gateway:jar:0.2.0: Failed to collect dependencies at org.slj:mqtt-sn-core:jar:0.2.0: Failed to read artifact descriptor for org.slj:mqtt-sn-core:jar:0.2.0: Could not find artifact org.slj:mqtt-sn:pom:0.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

Any dear?
Thanx for help.
System:
Ubuntu 20.04.5 LTS \n \l
mvn --version
Apache Maven 3.6.3

Is there a maven repro availabel?

BR

Andreas

**Comment by simon622** [comment]
Hi Andreas - Im working on getting this into maven central, but waiting on the sonatype domain being accepted. I will look into the above issue; in the meantime please download the full shaded artefact from the releases section; the gateway-0.2.0 build is fairly up to date.

**Comment by simon622** [comment]
Please try navigating into the parent project "mqtt-sn" and issue;

`mvn clean install` 

from the parent pom - this should cascade and build all dependencies.

**Comment by pfostenberg** [comment]
after update and the above command... 
Works -:)

**Comment by pfostenberg** [comment]
done.
